### ISSUE TITLE
Hardhat parameter may require adjustment

### ISSUE THREAD

**Issue by Vict0x** [mezo-org/validator-kit#11]
tools/hardhat/README.md 

running the command from the documentation results in an error:

```bash
npx hardhat --network testnet validatorPool:submitApplication --signer <validator address> --conspubkey <validator consensus address> --moniker <mezod moniker>
```
and

```bash
npx hardhat --network testnet validatorPool:application --signer <your validator address>
```

result in the following error:
```bash
Error HH305: Unrecognized param --signer
```
I think the parameter should be "operator" instead of "signer"

```bash
npx hardhat --network testnet validatorPool:submitApplication --operator <validator address> --conspubkey <validator consensus address> --moniker <mezod moniker>

npx hardhat --network testnet validatorPool:application --operator <your validator address>
```

**Comment by dimpar** [comment]
Thank you for reporting it! `validatorPool:submitApplication` task should take `--signer` as per coded [submitApplication task](https://github.com/mezo-org/validator-kit/blob/main/tools/hardhat/tasks/validatorpool.ts#L36). However, the `validatorPool:application` should indeed take the `--operator` flag as it was implemented [here](https://github.com/mezo-org/validator-kit/blob/main/tools/hardhat/tasks/validatorpool.ts#L22). I opened [PR](https://github.com/mezo-org/validator-kit/pull/13) with a fix.
